Task4
charapennikaurm/educational_practice pull request #3
Opened 2021-03-08 14:58 UTC by charapennikaurm

2021-03-09 10:35 UTC, smiakchilo requested changes

2021-03-09 10:35 UTC, smiakchilo commented on UI/css/style.css
> +body {
I believe the UI part does not belong to the task 4

2021-03-09 10:35 UTC, smiakchilo commented on UI/js/parallax.js-1.5.0/LICENSE
> +The MIT License (MIT)
Avoid adding 3rd party code to PR and probably to repository as well (if it's an NPM dependency, the mention in your project's `package.json` is enough)

2021-03-09 10:39 UTC, smiakchilo commented
Please always add meaningful commit messages (like "What exactly was added for what reason", up to 80-100 characters

2021-03-14 08:36 UTC, charapennikaurm commented on UI/css/style.css
> +body {
I'm still waiting for response for pull request with UI and hadn't figured out how to select commits for pull request

2021-03-14 21:22 UTC, smiakchilo commented
Easy)
1) You create the new branch not from the previous branch but from the master. I.e., first checkout master, then create new branch with git checkout -b “task4” etc. (or do the same via the IDEA interface)

2) If you  already committed to a “wrong” branch, you: 

- check out master

- create new branch

- do cherry-pick of only the needed commits from the wrong to the new branch



 

From: Roman ***@***.***> 
Sent: Sunday, March 14, 2021 11:37 AM
To: charapennikaurm/educational_practice ***@***.***>
Cc: Stepan Miakchilo ***@***.***>; Review requested ***@***.***>
Subject: Re: [charapennikaurm/educational_practice] Task4 (#3)

 

@charapennikaurm commented on this pull request.

  _____  

In UI/css/style.css <https://github.com/charapennikaurm/educational_practice/pull/3#discussion_r593863827> :

> @@ -0,0 +1,450 @@
+body {

I'm still waiting for response for pull request with UI and hadn't figured out how to select commits for pull request

—
You are receiving this because your review was requested.
Reply to this email directly, view it on GitHub <https://github.com/charapennikaurm/educational_practice/pull/3#discussion_r593863827> , or unsubscribe <https://github.com/notifications/unsubscribe-auth/ALUI6RBWHJHF3MYK2I5C5I3TDRYRJANCNFSM4YZRQD2Q> .


-- 


CONFIDENTIALITY
NOTICE: This email and files attached to it are 
confidential. If you
are not the intended recipient you are hereby notified 
that using,
copying, distributing or taking any action in reliance on the 
contents of this information is strictly prohibited. If you have
received 
this email in error please notify the sender and delete this
email.

2021-03-14 21:26 UTC, charapennikaurm commented
I have deleted UI files form this pull request, can I merge it now?

2021-03-14 21:28 UTC, smiakchilo commented
Yep, go ahead)

 

From: Roman ***@***.***> 
Sent: Monday, March 15, 2021 12:27 AM
To: charapennikaurm/educational_practice ***@***.***>
Cc: Stepan Miakchilo ***@***.***>; Review requested ***@***.***>
Subject: Re: [charapennikaurm/educational_practice] Task4 (#3)

 

I have deleted UI files form this pull request, can I merge it now?

—
You are receiving this because your review was requested.
Reply to this email directly, view it on GitHub <https://github.com/charapennikaurm/educational_practice/pull/3#issuecomment-798982811> , or unsubscribe <https://github.com/notifications/unsubscribe-auth/ALUI6RHYZTY2RJL37WWIKT3TDUSZJANCNFSM4YZRQD2Q> .


-- 


CONFIDENTIALITY
NOTICE: This email and files attached to it are 
confidential. If you
are not the intended recipient you are hereby notified 
that using,
copying, distributing or taking any action in reliance on the 
contents of this information is strictly prohibited. If you have
received 
this email in error please notify the sender and delete this
email.

2021-03-14 21:29 UTC, charapennikaurm commented
Thank you)

2021-03-14 21:33 UTC, merged